<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
			$heading = $this->placeholder('heading')->getValue();
			if(empty($heading)) {
				$heading = '';
			} else if(is_array($heading)) {
				$heading = implode(" ", $heading);
			}
			
			echo $this->headTitle($this->translate($heading))->setSeparator(' - ')->setAutoEscape(false)		
		?>
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
    </head>
	<body>
		<?php echo $this->content; ?>
	</body>
</html>